### ISSUE TITLE
INI mode

### ISSUE THREAD

**Issue by Rekseto** [uiw-react/react-codemirror#2]
There's no really good alternative for ini mode ;/

**Comment by jaywcjlove** [comment]
@Rekseto https://github.com/codemirror/CodeMirror/pull/462

It seems to be integrated.

**Comment by Rekseto** [comment]
Strange, in my node_modules/codemirror there's no mode like that, does this react-mirror depends on version where's support for INI files? Or Am i doing something wrong :/

**Comment by jaywcjlove** [comment]
@Rekseto  Set `mode='properties'`

**Comment by jaywcjlove** [comment]
Update `@uiw/react-codemirror@1.0.16` setting `properties` and `ini` effects are the same.

The new version automatically handles aliases.

@Rekseto
